heat_template_version: 2014-10-16

description: HOT to create sub-interfaces on a server instance using Contrail V2 plugin

parameters:
  vlan_tag_1:
    type: number
    default: 2222
  VMI_name_1:
    type: string
    default: test_vmi
  server_name:
    type: string
    default: test
  image:
    type: string
    default: cirros
  flavor:
    type: string
    default: m1.nano
  private_net_name_0:
    type: string
    default: test
  private_net_0:
    type: string
    default: "96a503f4-e9f2-49bb-80cb-d2f0c0775958"

resources:
  server_1:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: { get_param: private_net_0 }


  template_VirtualMachineInterface_1:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      name: { get_param: VMI_name_1 }
      virtual_network_refs: [{ get_param: private_net_0 }]
      virtual_machine_interface_properties:
        {
          virtual_machine_interface_properties_sub_interface_vlan_tag: { get_param: vlan_tag_1 },
        }
      virtual_machine_interface_mac_addresses:
        {
          virtual_machine_interface_mac_addresses_mac_address: [{ get_attr: [server_1, addresses, get_param: private_net_name_0, 0, "OS-EXT-IPS-MAC:mac_addr"] }],
        }
      virtual_machine_interface_refs: [{ get_attr: [server_1, addresses, get_param: private_net_name_0, 0, "port"] }]
