# Defaults for config options defined in CONFIG
$num_instances = 3
$instance_name_prefix = "ha-ubuntu"


if ENV["NUM_INSTANCES"].to_i > 0 && ENV["NUM_INSTANCES"]
  $num_instances = ENV["NUM_INSTANCES"].to_i
end

Vagrant.configure(2) do |config|
  # Contrail Box
  (1..$num_instances).each do |i|
    config.vm.define vm_name = "%s-%02d" % [$instance_name_prefix, i] do |config|
      config.vm.hostname = vm_name
      config.vm.box = "ubuntu/xenial64"
      config.vm.network "private_network", ip: "192.168.0.10%d" % i
    end
  end
end
