heat_template_version: '2017-02-24'
parameters:
  stackname:
    type: string
  name:
    type: string
  flavor:
    type: string
  image:
    type: string
  availability_zone:
    type: string
  public_net:
    type: string
  key_name:
    type: string
  deploy_net:
    type: string
  deploy_netip:
    type: string
  networks:
    type: json
  public_key:
    type: string
  private_key:
    type: string
  compute_count:
    type: string
  timeout:
    type: string
    default: 3600
  gluster_device:
    type: string
    default: /dev/vdb
  vol_size:
    type: string
    default: 50
  compute:
    type: boolean
    default: true
conditions:
  ifCompute:
    equals:
     - get_param: compute
     - true
outputs:
  floating_ip_address:
    value:
      get_attr: [floating_ip, floating_ip_address]
  server_id:
    value:
      get_resource: server
resources:
  server:
    type: OS::Nova::Server
    properties:
      availability_zone: { get_param: availability_zone}
      flavor: { get_param: flavor}
      image: { get_param: image}
      key_name: {get_param: key_name}
      name: 
        str_replace:
          template: stacknamename
          params:
            stackname: { get_param: stackname }
            name: { get_param: name }
      networks: 
      - port: { get_resource: deploy_netport }
      user_data: {get_resource: cloud_config}
      user_data_format: RAW
  deploy_netport:
    properties:
      network: {get_param: deploy_net}
      fixed_ips: [ {  "ip_address": { get_param: deploy_netip } } ]
      security_groups: 
      - { get_resource: security_group}      
    type: OS::Neutron::Port
  floating_ip:
    properties: {floating_network: { get_param: public_net }}
    type: OS::Neutron::FloatingIP
  floating_ip_asociate:
    properties:
      floatingip_id: {get_resource: floating_ip}
      port_id: { get_resource: deploy_netport }
    type: OS::Neutron::FloatingIPAssociation
  security_group_random:
    type: OS::Heat::RandomString
  security_group:
    properties:
      name:
        get_attr: [security_group_random, value]
      rules:
      - {port_range_max: 65535, port_range_min: 0, protocol: tcp, remote_ip_prefix: 0.0.0.0/0}
      - {port_range_max: 65535, port_range_min: 0, protocol: udp, remote_ip_prefix: 0.0.0.0/0}
      - {protocol: icmp, remote_ip_prefix: 0.0.0.0/0}
    type: OS::Neutron::SecurityGroup
  cloud_config:
    properties:
      parts:
      - config: { get_resource: initial_config }
      - config: { get_resource: common_config }
      - config: { get_resource: k8s_config }
      - config: { get_resource: gluster_config }
      - config: { get_resource: complete_config }
    type: OS::Heat::MultipartMime
  initial_config:
    properties:
      cloud_config:
        disable_root: 0
        package_upgrade: true
        run_cmd : []
        write_files:
        - path: /root/.ssh/id_rsa
          permissions: 0600
          content:
            get_param: private_key
        - path: /root/.ssh/authorized_keys
          permissions: 0600
          content:
            get_param: public_key
    type: OS::Heat::CloudConfig
  common_config:
    properties:
      config:
        str_replace:
          params:
            stackname: { get_param: stackname }
            servercount: { get_param: compute_count }
            control_hostname:   { get_param: [ networks, deploy_net , hosts, control, name]}
            contrail_hostname:  { get_param: [ networks, deploy_net , hosts, contrail, name]}
            compute_hostname:  { get_param: [ networks, deploy_net , hosts, compute, name]}
            contrail_device: { get_param: [ networks, deploy_net , device]}
            control_ip:  { get_param: [ networks, deploy_net , hosts, control, ip]}
            contrail_ip: { get_param: [ networks, deploy_net , hosts, contrail, ip]}
            compute_ip: { get_param: [ networks, deploy_net , hosts, compute, ipprefix]}
            docker_bridge_ip: { get_param: [ networks, docker_bridge ]}
          template: 
            get_file: common.sh 
    type: OS::Heat::SoftwareConfig
  k8s_config:
    properties:
      config:
        str_replace:
          params:
            stackname: { get_param: stackname }
            servercount: { get_param: compute_count }
            control_hostname:   { get_param: [ networks, deploy_net , hosts, control, name]}
            contrail_hostname:  { get_param: [ networks, deploy_net , hosts, contrail, name]}
            compute_hostname:  { get_param: [ networks, deploy_net , hosts, compute, name]}
            contrail_device: { get_param: [ networks, deploy_net , device]}
            control_ip:  { get_param: [ networks, deploy_net , hosts, control, ip]}
            contrail_ip: { get_param: [ networks, deploy_net , hosts, contrail, ip]}
            compute_ip: { get_param: [ networks, deploy_net , hosts, compute, ipprefix]}
            docker_bridge_ip: { get_param: [ networks, docker_bridge ]}
          template:
            get_file: k8s.sh
    type: OS::Heat::SoftwareConfig
  gluster_config:
    properties:
      config:
        str_replace:
          params:
            stackname: { get_param: stackname }
            servercount: { get_param: compute_count }
            control_hostname:   { get_param: [ networks, deploy_net , hosts, control, name]}
            contrail_hostname:  { get_param: [ networks, deploy_net , hosts, contrail, name]}
            compute_hostname:  { get_param: [ networks, deploy_net , hosts, compute, name]}
            contrail_device: { get_param: [ networks, deploy_net , device]}
            control_ip:  { get_param: [ networks, deploy_net , hosts, control, ip]}
            contrail_ip: { get_param: [ networks, deploy_net , hosts, contrail, ip]}
            compute_ip: { get_param: [ networks, deploy_net , hosts, compute, ipprefix]}
            docker_bridge_ip: { get_param: [ networks, docker_bridge ]}
            gluster_device: { get_param: gluster_device }
          template:
            get_file: gluster.sh
    type: OS::Heat::SoftwareConfig
  complete_config:
    properties:
      config:
        str_replace:
          params:
            wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }
          template: | 
            !/bin/sh
            wc_notify --data-binary '{"status": "SUCCESS"}'
    type: OS::Heat::SoftwareConfig
  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: wait_handle}
      timeout: { get_param: timeout }
  wait_handle:
    type: OS::Heat::WaitConditionHandle
  vol:
    type: OS::Cinder::Volume
    condition: ifCompute
    properties:
     size: { get_param: vol_size }
  vol_attach:
    type: OS::Cinder::VolumeAttachment
    condition: ifCompute
    properties:
      instance_uuid: { get_resource: server }
      volume_id: { get_resource: vol }

