# Defaults for config options defined in CONFIG
$num_instances = 2
$instance_name_prefix = "maas-client"


if ENV["NUM_INSTANCES"].to_i > 0 && ENV["NUM_INSTANCES"]
  $num_instances = ENV["NUM_INSTANCES"].to_i
end

Vagrant.configure(2) do |config|
  # Contrail Box
  config.vm.define vm_name = "cfg01" do |cfg01|
    cfg01.vm.hostname = vm_name
    cfg01.vm.box = "ubuntu/xenial64"
    cfg01.vm.network "private_network", ip: "192.168.22.10" 
    cfg01.vm.provider "virtualbox" do |pmv|
      pmv.memory = 4096
      pmv.cpus = 4
    end
  end

  (1..3).each do | i |
    config.vm.define vm_name = "cnt%s" % i do |cnt|
      cnt.vm.hostname = vm_name
      cnt.vm.box = "ubuntu/xenial64"
      cnt.vm.network "private_network", ip: "192.168.22.10%s" % i
      cnt.vm.provider "virtualbox" do |pmv|
        pmv.memory = 4096
        pmv.cpus = 4
      end
    end
  end

  (1..2).each do | i |
    config.vm.define vm_name = "cmp%s" % i do |cmp|
      cmp.vm.hostname = vm_name
      cmp.vm.box = "ubuntu/xenial64"
      cmp.vm.network "private_network", ip: "192.168.22.20%s" % i
      cmp.vm.provider "virtualbox" do |pmv|
        pmv.memory = 4096
        pmv.cpus = 4
      end
    end
  end


end
